run:
	python3 hello_world.py


test:
	python3 s3_move.py --src dev-et-data/in/north_america_data/temperature --dst dev-et-data/in/north_america_data/temperature/daily

now:
	python3 s3_move.py --src dev-et-data/in/north_america_data/temperature --dst dev-et-data/in/NorthAmerica/Temp

ppt:
	 python3 s3_move.py --src dev-et-data/in/north_america_data/precipitation/2001/ --dst dev-et-data/in/NorthAmerica/PPT/daily/2001/
